name: CI-Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: ğŸ” Linting Job
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout code
        uses: actions/checkout@v4
      - name:  Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name:  Install dependencies
        run: npm install --legacy-peer-deps
      - name:  Run Linter
        run: npm run lint && echo " Linting completed successfully"

  test:
    name:  Testing Job
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name:  Checkout code
        uses: actions/checkout@v4
      - name:  Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name:  Run Jest Tests
        run: npm test && echo  Jest tests completed successfully"

  deploy:
    name: ğŸš€ Deployment Job
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Simulate Deployment
        run: echo  "Deployment successful"
